# Usual compilation flags
CFLAGS = -Wall -Wextra -g -std=c99
CPPFLAGS =
LDFLAGS = -lgmp
EXE = PIR
OBJ = Paillier.o PIR_Naive.o PIR_2D.o PIR_3D.o PIR_XD.o Build_DBMS.o main.o

# Special rules and targets
.PHONY: all paillier clean help

# Rules and targets
all: $(EXE)

$(EXE): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

Paillier.o: Paillier.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

PIR_Naive.o: PIR_Naive.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

PIR_2D.o: PIR_2D.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

PIR_3D.o: PIR_3D.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

PIR_XD.o: PIR_XD.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

Build_DBMS.o: Build_DBMS.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

main.o: main.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $^

clean:
	@rm -f *~ *.o $(EXE) leaktest.c a.out
	@rm -rf .DS_Store
	@rm -rf *.dSYM *.gch .yxy gdb.txt

help:
	@echo "Makefile Usage:"
	@echo "- make [all]\t\tStart the compilation"
	@echo "- make clean\t\tRemove all files generated by make"
	@echo "- make help\t\tDisplay this help"
